import assert from 'node:assert/strict';
import {saveFavoriteFood,deleteFavoriteFood} from '../src/favorite-foods.js';
let list=saveFavoriteFood(undefined,' 밥  반공기 ');
assert.equal(list[0].food,'밥 반공기');
assert.equal(saveFavoriteFood(list,'밥 반공기'),list);
assert.equal(saveFavoriteFood(list,'   '),list);
const saved=JSON.parse(JSON.stringify({meals:[],favoriteFoods:list}));
assert.equal(saved.meals.length,0);
assert.deepEqual(saved.favoriteFoods,list);
const original=list[0];
const edited=saveFavoriteFood(list,'밥 1공기',original.id);
assert.equal(edited[0].id,original.id);
assert.equal(edited[0].food,'밥 1공기');
assert.equal(original.food,'밥 반공기');
assert.deepEqual(deleteFavoriteFood(edited,original.id),[]);
assert.equal('analysis' in original,false);
console.log('PASS: independent favorites registration, duplicate/empty rejection, edit, delete and snapshot persistence');

const {toggleFavoriteFood,isFavoriteSelected}=await import('../src/favorite-foods.js');
let meal=toggleFavoriteFood('밥 한공기','컵 방울토마토');
assert.equal(meal,'밥 한공기, 컵 방울토마토');
meal=toggleFavoriteFood(meal,'된장, 바지락국');
assert.equal(meal,'밥 한공기, 컵 방울토마토, 된장, 바지락국');
assert.ok(isFavoriteSelected(meal,'된장, 바지락국'));
assert.equal(isFavoriteSelected(meal,'밥 반공기'),false);
assert.equal(toggleFavoriteFood(meal,'컵 방울토마토'),'밥 한공기, 된장, 바지락국');
assert.equal(toggleFavoriteFood(meal,'밥 한공기'),'컵 방울토마토, 된장, 바지락국');
assert.equal(toggleFavoriteFood(meal,'된장, 바지락국'),'밥 한공기, 컵 방울토마토');
assert.equal(toggleFavoriteFood('밥 한공기','밥 한공기'),'');
assert.equal(toggleFavoriteFood('계란 1개','밥 한공기'),'계란 1개, 밥 한공기');
assert.ok(isFavoriteSelected('밥 한공기\n계란 1개','계란 1개'));
assert.ok(isFavoriteSelected('우유 (200ml), 밥 한공기','우유 (200ml)'));
console.log('PASS: multi-selection, exact selection state, removal at every position, comma-containing foods, typed text preservation');
