import assert from 'node:assert/strict';
import {mealHistoryOptions,copyMealHistory} from '../src/meal-history.js';
import {scaleMealText} from '../src/portions.js';
const old={food:'아몬드 1봉',date:'2026-10-06',analysis:{kcal:200}};
const latest={food:'아몬드  1봉',date:'2026-10-08',analysis:{kcal:230,items:[{name:'아몬드',portion:'1봉',kcal:230}]}};
const meals=[old,{food:'밥 반공기',date:'2026-10-07'},latest,{food:'  '}];
assert.deepEqual(mealHistoryOptions(meals),[latest,meals[1]]);
assert.deepEqual(mealHistoryOptions(meals,'아몬드'),[latest]);
assert.deepEqual(mealHistoryOptions([],''),[]);
assert.deepEqual(mealHistoryOptions(meals,'없는 음식'),[]);
const copy=copyMealHistory(latest);
assert.equal(copy.analysis.kcal,230);
assert.equal(scaleMealText(copy.analysis,copy.food,'아몬드 반봉지').kcal,115);
copy.analysis.items[0].kcal=1;
assert.equal(latest.analysis.items[0].kcal,230);
assert.equal(copyMealHistory(meals[1]).analysis,null);
assert.equal('id' in copy,false);
assert.equal('date' in copy,false);
console.log('PASS: meal history ordering, deduplication, search, independent copies and portion scaling');
