import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const {nutritionTargets,latestWeight,intakeStatus}=await import('data:text/javascript;base64,'+Buffer.from(readFileSync(new URL('../src/nutrition.js',import.meta.url))).toString('base64'));
const today='2026-09-30',d={weight:[{date:'2026-09-28',value:'60'},{date:'2026-09-27',value:'65'},{date:'2026-10-01',value:'80'}]};
assert.equal(latestWeight(d,{},today).value,60);
assert.equal(latestWeight(d,{history:[{date:today,weight:61}]},today).value,61);
assert.equal(latestWeight({weight:[{date:today,value:62}]},{history:[{date:today,weight:61}]},today).value,62);
assert.equal(nutritionTargets(d,{},today).configured,false);
const b=nutritionTargets({...d,nutrition:{bmr:'1500',activity:'1.55',goalWeight:'63.6'}},{},today);
assert.equal(b.kcal,2525);assert.equal(b.adjustment,200);
const m=nutritionTargets({...d,nutrition:{age:'50',sex:'male',height:'170',goalWeight:'60'}},{},today);
assert.equal(m.bmr,1418);assert.equal(m.kcal,1701);
const f=nutritionTargets({...d,nutrition:{age:'50',sex:'female',height:'170',goalWeight:'60'}},{},today);
assert.equal(f.bmr,1252);
assert.equal(nutritionTargets({...d,nutrition:{age:'50',sex:'',height:'170'}},{},today).configured,false);
assert.equal(intakeStatus(600,1800,false),'남은 1200');assert.equal(intakeStatus(600,1800,true),'부족');
assert.equal(intakeStatus(2000,1800,false),'목표 초과 200');
assert.ok(Math.abs(b.protein*4+b.carbs*4+b.fat*9-b.kcal)<=2);
console.log('PASS: newest valid weight, InBody/formula/fallback, activity/goal adjustment, macro energy, recording/completion');
